export const US_STATES = [
  { code: "AL", label: "Alabama" },
  { code: "AK", label: "Alaska" },
  { code: "AZ", label: "Arizona" },
  { code: "AR", label: "Arkansas" },
  { code: "CA", label: "California" },
  { code: "CO", label: "Colorado" },
  { code: "CT", label: "Connecticut" },
  { code: "DE", label: "Delaware" },
  { code: "DC", label: "Distrito de Columbia" },
  { code: "FL", label: "Florida" },
  { code: "GA", label: "Georgia" },
  { code: "HI", label: "Hawái" },
  { code: "ID", label: "Idaho" },
  { code: "IL", label: "Illinois" },
  { code: "IN", label: "Indiana" },
  { code: "IA", label: "Iowa" },
  { code: "KS", label: "Kansas" },
  { code: "KY", label: "Kentucky" },
  { code: "LA", label: "Luisiana" },
  { code: "ME", label: "Maine" },
  { code: "MD", label: "Maryland" },
  { code: "MA", label: "Massachusetts" },
  { code: "MI", label: "Míchigan" },
  { code: "MN", label: "Minnesota" },
  { code: "MS", label: "Misisipi" },
  { code: "MO", label: "Misuri" },
  { code: "MT", label: "Montana" },
  { code: "NE", label: "Nebraska" },
  { code: "NV", label: "Nevada" },
  { code: "NH", label: "New Hampshire" },
  { code: "NJ", label: "Nueva Jersey" },
  { code: "NM", label: "Nuevo México" },
  { code: "NY", label: "Nueva York" },
  { code: "NC", label: "Carolina del Norte" },
  { code: "ND", label: "Dakota del Norte" },
  { code: "OH", label: "Ohio" },
  { code: "OK", label: "Oklahoma" },
  { code: "OR", label: "Oregón" },
  { code: "PA", label: "Pensilvania" },
  { code: "RI", label: "Rhode Island" },
  { code: "SC", label: "Carolina del Sur" },
  { code: "SD", label: "Dakota del Sur" },
  { code: "TN", label: "Tennessee" },
  { code: "TX", label: "Texas" },
  { code: "UT", label: "Utah" },
  { code: "VT", label: "Vermont" },
  { code: "VA", label: "Virginia" },
  { code: "WA", label: "Washington" },
  { code: "WV", label: "Virginia Occidental" },
  { code: "WI", label: "Wisconsin" },
  { code: "WY", label: "Wyoming" },
] as const;

export function stateLabel(code: string | null | undefined): string {
  if (!code) return "";
  return US_STATES.find((s) => s.code === code)?.label ?? code;
}
