// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma Migrate/CLI needs a direct (non-pooled) connection to Postgres.
    // The app itself connects via DATABASE_URL (pooled) using the pg adapter, see src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
